package ventanaG;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class InterfazPrincipal extends javax.swing.JFrame {
    
    //Variables publicas
    String filePath = "";
    String contenidoTextArea = "";
    String validacionAnalizador = "";
    String archivoElegido = "";
    //Fin Variables publicas
    
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaConsola = new javax.swing.JTextArea();
        mPestanas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        entradaTextoP = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoArchivo = new javax.swing.JMenuItem();
        abrirArchivo = new javax.swing.JMenuItem();
        guardarArchivo = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        realizaEjecucion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        reporteToken = new javax.swing.JMenuItem();
        reporteErrores = new javax.swing.JMenuItem();
        reporteTablaS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 28, 31));
        jPanel1.setForeground(new java.awt.Color(50, 46, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("Entrada");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 0));
        jLabel2.setText("Ver Graficas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 0));
        jLabel3.setText("Consola");

        salidaConsola.setEditable(false);
        salidaConsola.setBackground(new java.awt.Color(153, 153, 153));
        salidaConsola.setColumns(20);
        salidaConsola.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        salidaConsola.setRows(5);
        jScrollPane1.setViewportView(salidaConsola);

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 153));

        entradaTextoP.setBackground(new java.awt.Color(153, 153, 153));
        entradaTextoP.setColumns(20);
        entradaTextoP.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        entradaTextoP.setRows(5);
        jScrollPane2.setViewportView(entradaTextoP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mPestanas.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mPestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mPestanas, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jMenu1.setText("Archivo");

        nuevoArchivo.setText("Nuevo Archivo");
        nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoArchivo);

        abrirArchivo.setText("Abrir Archivo");
        abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivo);

        guardarArchivo.setText("Guardar");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(guardarArchivo);

        guardarComo.setText("Guardar Como");
        guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(guardarComo);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ejecutar");

        realizaEjecucion.setText("Realizar Ejecución");
        realizaEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaEjecucionActionPerformed(evt);
            }
        });
        jMenu3.add(realizaEjecucion);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Reportes");

        reporteToken.setText("Reporte de Tokens");
        jMenu2.add(reporteToken);

        reporteErrores.setText("Reporte de Errores");
        jMenu2.add(reporteErrores);

        reporteTablaS.setText("Reporte Tabla de Simbolos");
        jMenu2.add(reporteTablaS);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchivoActionPerformed
        //Nuevo archivo
        //1. abrirá una pestaña en blanco
        
    }//GEN-LAST:event_nuevoArchivoActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        contenidoTextArea = entradaTextoP.getText();
        if (contenidoTextArea.equals("")) {
            System.out.println("No hay datos para guardar");
        } else {
            try {
                FileWriter escribir = new FileWriter(filePath);
                escribir.write(contenidoTextArea); //Para convertir a minuscula agregar a la variable string .toLowerCase()
                escribir.close();
            } catch (IOException e) {
                System.out.println("Ha ocurrido un error al guardar los datos en el archivo." + e);
            }
        }
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoActionPerformed
        JFileChooser elegirArchivo = new JFileChooser();
        int valuar = elegirArchivo.showSaveDialog(this);
        if (valuar == JFileChooser.APPROVE_OPTION) {
            //Obtiene la ruta del archivo junto con la extensión ingresada
            File selectFile = elegirArchivo.getSelectedFile();
            //Escribiendo el archivo en la ruta
            try {
                contenidoTextArea = entradaTextoP.getText();
                FileWriter escribir = new FileWriter(selectFile);
                escribir.write(contenidoTextArea);
                escribir.close();
            } catch (IOException e) {
                System.out.println("Ha ocurrido un error al guardar los datos en el archivo." + e);
            }
        } else {
            //se muestra 
            //nombreArchivo.setText("Archivo no guardado");
        }
    }//GEN-LAST:event_guardarComoActionPerformed

    private void abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoActionPerformed
        JFileChooser elegirArchivo = new JFileChooser();
        FileNameExtensionFilter data = new FileNameExtensionFilter("Tipos","df");
        elegirArchivo.setFileFilter(data);
//        elegirArchivo.addChoosableFileFilter(data);
        int valuado = elegirArchivo.showOpenDialog(this);

        if (valuado == JFileChooser.APPROVE_OPTION) {
//            System.out.println("Archivo Seleccionado: " + elegirArchivo.getSelectedFile().getName());
            archivoElegido = elegirArchivo.getSelectedFile().getName();
            //nombreArchivo.setText(archivoElegido);
            File selectFile = elegirArchivo.getSelectedFile();
            filePath = selectFile.getAbsolutePath();

            try {
                BufferedReader leer = new BufferedReader(new InputStreamReader(new FileInputStream(filePath), "UTF-8"));
                String linea;
                String parrafo = "";
                while ((linea = leer.readLine()) != null) {
                    parrafo += linea + "\n";
                }
                leer.close();
                entradaTextoP.setText(parrafo);
            } catch (IOException e) {
                System.out.println("" + e.getMessage());
            }
        } else {
            //
            //nombreArchivo.setText("Archivo no seleccionado"); 
        }
    }//GEN-LAST:event_abrirArchivoActionPerformed

    private void realizaEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaEjecucionActionPerformed
        proyecto.pkg1.Proyecto1.analizar(entradaTextoP.getText());
        salidaConsola.setText(entradaTextoP.getText());
    }//GEN-LAST:event_realizaEjecucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArchivo;
    private javax.swing.JTextArea entradaTextoP;
    private javax.swing.JMenuItem guardarArchivo;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane mPestanas;
    private javax.swing.JMenuItem nuevoArchivo;
    private javax.swing.JMenuItem realizaEjecucion;
    private javax.swing.JMenuItem reporteErrores;
    private javax.swing.JMenuItem reporteTablaS;
    private javax.swing.JMenuItem reporteToken;
    private javax.swing.JTextArea salidaConsola;
    // End of variables declaration//GEN-END:variables
}
